[workspace]
authors = ["Josh S Wilkinson <joshswilkinson@pm.me>"]
channels = [
  "https://conda.modular.com/max",
  "https://repo.prefix.dev/modular-community",
  "conda-forge",
]

name = "hyprmenu"
platforms = ["linux-64"]

[tasks]
main = "mojo hyprmenu.mojo"
build = "mojo build hyprmenu.mojo -o ./build/hyprmenu"
install = "cp ./build/hyprmenu ~/.local/bin"

[dependencies]
mojo = ">=25.5.0"
emberjson = ">=0.1.5,<0.2"
